# Generated by Django 4.1.7 on 2024-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('jntu_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('current_semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('elective_name', models.CharField(max_length=100)),
                ('offering_department', models.CharField(max_length=100)),
                ('offering_strength', models.IntegerField()),
                ('not_allowed_students', models.ManyToManyField(blank=True, to='home.student')),
            ],
        ),
    ]
